// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5N4s8i_pKg5YNigmOqzh6iSrL7RGsIhE',
    appId: '1:612550486968:web:4a5a0e520f1dc76f587d4d',
    messagingSenderId: '612550486968',
    projectId: 'todoapp-c93a2',
    authDomain: 'todoapp-c93a2.firebaseapp.com',
    storageBucket: 'todoapp-c93a2.firebasestorage.app',
    measurementId: 'G-7GSNJGQ3LK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeUzO4U2CFF3Sugm5KHXLNuLm4qkUUuI8',
    appId: '1:612550486968:android:cb909994a95326e6587d4d',
    messagingSenderId: '612550486968',
    projectId: 'todoapp-c93a2',
    storageBucket: 'todoapp-c93a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiVH96IzowBDS9o8p_Nyfdc6lWwSgtR5k',
    appId: '1:612550486968:ios:4c1d1b675b0e2179587d4d',
    messagingSenderId: '612550486968',
    projectId: 'todoapp-c93a2',
    storageBucket: 'todoapp-c93a2.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiVH96IzowBDS9o8p_Nyfdc6lWwSgtR5k',
    appId: '1:612550486968:ios:4c1d1b675b0e2179587d4d',
    messagingSenderId: '612550486968',
    projectId: 'todoapp-c93a2',
    storageBucket: 'todoapp-c93a2.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5N4s8i_pKg5YNigmOqzh6iSrL7RGsIhE',
    appId: '1:612550486968:web:1cd376738cb02695587d4d',
    messagingSenderId: '612550486968',
    projectId: 'todoapp-c93a2',
    authDomain: 'todoapp-c93a2.firebaseapp.com',
    storageBucket: 'todoapp-c93a2.firebasestorage.app',
    measurementId: 'G-EKRYP9KXKR',
  );

}